# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'GTMMap' do
pod 'AFNetworking'
pod 'JSONModel'
pod 'CocoaLumberjack'
pod 'SVProgressHUD'
pod 'FFCircularProgressView', '>= 0.1'
pod 'FMDB'
pod 'GoogleMaps'
pod 'Charts'
#pod 'TWRDownloadManager'
end

target 'GTMMapTests' do

end

target 'GTMMapUITests' do

end

